### ISSUE TITLE
Arena debug-file

### ISSUE THREAD

**Issue by yellow-panther** [louism33/chessPlusPlus#1]
Hello loiusm33,
which JRE version is suitable for Windows 7 32/64 bit OS? cf. http://talkchess.com/forum3/viewtopic.php?f=2&t=68895 

regards

**Comment by louism33** [comment]
Hello yellow panther,
You will need jre 10 for this! Thank you for your interest,

Louis

**Comment by louism33** [comment]
Hi Panther, I have now set the Java version to 8 in the pom. Please let me know if your issue is resolved :)
